### ISSUE TITLE
`make install` target missing?

### ISSUE THREAD

**Issue by nonproftechie** [jamrizzi/wp-plugin-devkit#1]
![image](https://user-images.githubusercontent.com/13720633/30312212-1d20d14e-975e-11e7-9321-7af4292180a7.png)

**Comment by clayrisser** [comment]
There is no `make install`. That was an error in my documentation.

It should be . . .

```sh
make init
make start
```

Docs fixed with . . .
a5c2ee31c190aebed6358237ac93a6e368ad4d3c
efe3f4e89f33bc9810b0558ba3a17534e55e2101
